# Factores


```{r, include = FALSE}
library(tidyverse)
library(datos)
```


## Encuesta social general

### Ejercicios

1. Explora la distribución de `ingreso`. ¿Qué hace que el gráfico de barras por defecto sea tan difícil de comprender? ¿Cómo podrías mejorarlo?

<div class="solucion">
<h3>Solución</h3>

</div>


1. ¿Cuál es la `religion` más común de la encuesta? ¿Cuál es el `partido` más común?


<div class="solucion">
<h3>Solución</h3>

</div>

1. ¿A qué `religion` se aplica cada `denominacion`? ¿Cómo puedes encontrarlo con una tabla? ¿Cómo lo puedes descubrir con una visualización?

<div class="solucion">
<h3>Solución</h3>

</div>

## Modificar el orden de los factores


### Ejercicios

1. Hay algunos números sospechosamente grandes en `horas_tv`. ¿Es la media un buen resumen?

<div class="solucion">
<h3>Solución</h3>

</div>


1. Identifica, para cada factor en `encuesta`, si el orden de los niveles es arbitrario o responde a algún principio.

<div class="solucion">
<h3>Solución</h3>

</div>


1. ¿Por qué mover "No aplica" al inicio de los niveles lo llevó al final del gráfico?

<div class="solucion">
<h3>Solución</h3>

</div>


## Modificar los niveles de los factores


### Ejercicios

1. ¿Cómo han cambiado en el tiempo las proporciones de personas que se identifican como Demócratas, Republicanas e Independientes?

<div class="solucion">
<h3>Solución</h3>

</div>


1. ¿Cómo podrías colapsar `ingreso` en un grupo más pequeño de categorías?

<div class="solucion">
<h3>Solución</h3>

</div>
